<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "action_log".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $role
 * @property string $username
 * @property string $controller
 * @property string $action
 * @property string $information
 * @property string $status
 * @property string $timestamp
 * @property string $aliasModel
 */
abstract class ActionLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'action_log';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'role', 'username', 'controller', 'action', 'information', 'status'], 'required'],
            [['user_id'], 'integer'],
            [['information'], 'string'],
            [['timestamp'], 'safe'],
            [['role', 'username', 'controller'], 'string', 'max' => 100],
            [['action'], 'string', 'max' => 50],
            [['status'], 'string', 'max' => 40]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'role' => 'Role',
            'username' => 'Username',
            'controller' => 'Controller',
            'action' => 'Action',
            'information' => 'Information',
            'status' => 'Status',
            'timestamp' => 'Timestamp',
        ];
    }




}
