<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_kecamatan".
 *
 * @property string $id
 * @property string $kota_id
 * @property string $nama
 *
 * @property \app\models\Profile[] $profiles
 * @property \app\models\WilayahDesa[] $wilayahDesas
 * @property \app\models\WilayahKota $kota
 * @property string $aliasModel
 */
abstract class WilayahKecamatan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_kecamatan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'kota_id', 'nama'], 'required'],
            [['id'], 'string', 'max' => 7],
            [['kota_id'], 'string', 'max' => 4],
            [['nama'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['kota_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahKota::className(), 'targetAttribute' => ['kota_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kota_id' => 'Kota ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfiles()
    {
        return $this->hasMany(\app\models\Profile::className(), ['kecamatan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahDesas()
    {
        return $this->hasMany(\app\models\WilayahDesa::className(), ['kecamatan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKota()
    {
        return $this->hasOne(\app\models\WilayahKota::className(), ['id' => 'kota_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\WilayahKecamatanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\WilayahKecamatanQuery(get_called_class());
    }


}
