<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_desa".
 *
 * @property string $id
 * @property string $kecamatan_id
 * @property string $nama
 *
 * @property \app\models\Profile[] $profiles
 * @property \app\models\WilayahKecamatan $kecamatan
 * @property string $aliasModel
 */
abstract class WilayahDesa extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_desa';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'kecamatan_id', 'nama'], 'required'],
            [['id'], 'string', 'max' => 10],
            [['kecamatan_id'], 'string', 'max' => 7],
            [['nama'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['kecamatan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahKecamatan::className(), 'targetAttribute' => ['kecamatan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kecamatan_id' => 'Kecamatan ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfiles()
    {
        return $this->hasMany(\app\models\Profile::className(), ['desa_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKecamatan()
    {
        return $this->hasOne(\app\models\WilayahKecamatan::className(), ['id' => 'kecamatan_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\WilayahDesaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\WilayahDesaQuery(get_called_class());
    }


}
