<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_provinsi".
 *
 * @property string $id
 * @property string $nama
 *
 * @property \app\models\Profile[] $profiles
 * @property \app\models\WilayahKota[] $wilayahKotas
 * @property string $aliasModel
 */
abstract class WilayahProvinsi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_provinsi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'nama'], 'required'],
            [['id'], 'string', 'max' => 2],
            [['nama'], 'string', 'max' => 255],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfiles()
    {
        return $this->hasMany(\app\models\Profile::className(), ['provinsi_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahKotas()
    {
        return $this->hasMany(\app\models\WilayahKota::className(), ['provinsi_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\WilayahProvinsiQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\WilayahProvinsiQuery(get_called_class());
    }


}
