<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_kota".
 *
 * @property string $id
 * @property string $provinsi_id
 * @property string $nama
 *
 * @property \app\models\Profile[] $profiles
 * @property \app\models\WilayahKecamatan[] $wilayahKecamatans
 * @property \app\models\WilayahProvinsi $provinsi
 * @property string $aliasModel
 */
abstract class WilayahKota extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_kota';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'provinsi_id', 'nama'], 'required'],
            [['id'], 'string', 'max' => 4],
            [['provinsi_id'], 'string', 'max' => 2],
            [['nama'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['provinsi_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahProvinsi::className(), 'targetAttribute' => ['provinsi_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'provinsi_id' => 'Provinsi ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfiles()
    {
        return $this->hasMany(\app\models\Profile::className(), ['kota_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahKecamatans()
    {
        return $this->hasMany(\app\models\WilayahKecamatan::className(), ['kota_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvinsi()
    {
        return $this->hasOne(\app\models\WilayahProvinsi::className(), ['id' => 'provinsi_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\WilayahKotaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\WilayahKotaQuery(get_called_class());
    }


}
